import { createContext, useContext } from "react";

/* ── i18n ─────────────────────────────────────────────────────────────────── */
const LANGS = {
  es: {
    code:"es", flag:"🇪🇸", name:"Español",
    tagline:"Sin registro · Sin marcas de agua · 100% privado",
    hero_h1a:"La forma más rápida de", hero_h1b:"convertir tus archivos.",
    hero_sub:"PDF, Word, Excel, imágenes. Gratis para archivos de hasta 10 MB. Sin que tus archivos salgan de tu navegador.",
    hero_cta:"Empezar gratis",
    hero_drop:"Arrastra cualquier archivo aquí",
    hero_drop_sub:"Selección automática de herramienta",
    tools_title:"Herramientas", tools_count:"disponibles",
    detected:"Detectado",
    unknown_fmt:"Formato no reconocido",
    incompat:"Formato no compatible",
    drag_single:"Arrastra tu archivo aquí",
    drag_multi:"Arrastra tus archivos aquí",
    click_hint:"o haz clic",
    processing:"Procesando…",
    convert:"Convertir", cancel:"Cancelar",
    download:"Descargar", other:"Otro archivo",
    done_title:"Listo para descargar",
    done_sub_s:"archivo procesado", done_sub_p:"archivos procesados",
    conv_done:"Conversión completada",
    dl_started:"Descarga iniciada",
    pages_label:"Rango de páginas (ej: 1-3, 5, 7-9)",
    pages_ph:"Vacío = todas las páginas",
    compress_level:"Nivel de compresión",
    q_low:"Suave", q_med:"Media", q_high:"Máxima",
    feat:[ ["Procesado local","Tus archivos no salen del navegador."],
           ["Formato conservado","Fuentes, márgenes y tablas intactos."],
           ["Descarga inmediata","Resultado listo en segundos."],
           ["Sin publicidad","Plan gratuito sin anuncios."] ],
    max_size:"máx. 200 MB",
    counter:"archivos convertidos",
    step_read:"Leyendo archivo…", step_proc:"Procesando…", step_done:"¡Listo!",
    hist_title:"Conversiones recientes", hist_empty:"Aún no has convertido ningún archivo.", hist_clear:"Borrar historial",
    free_limit:"El archivo supera el límite de 10 MB del plan gratuito.",
    free_batch:"El plan gratuito permite unir hasta 2 archivos. Actualiza a Pro para unir archivos ilimitados.",
    free_size:"El archivo supera el límite de 10 MB del plan gratuito.",
    upgrade_cta:"Ver planes Pro",
    upgrade_sub:"Ilimitado · Archivos hasta 200 MB · Sin publicidad",
    plan_free:"Gratis", plan_pro:"Pro",
    plan_free_desc:"Para uso ocasional",
    plan_pro_desc:"Para uso profesional",
    plan_monthly:"al mes", plan_yearly:"al año",
    plan_save:"Ahorra 25%",
    plan_cta_free:"Empezar gratis",
    plan_cta_pro:"Empezar con Pro",
    plan_current:"Plan actual",
    feat_batch:"Unir hasta 2 archivos",
    merge_hint:"Plan gratuito: máx. 2 archivos. Actualiza a Pro para más.",
    feat_size_free:"Archivos hasta 10 MB",
    feat_size_pro:"Archivos hasta 200 MB",
    feat_tools:"Todas las herramientas",
    feat_unlimited:"Unir archivos ilimitados",
    feat_noad:"Sin publicidad",
    feat_priority:"Procesamiento prioritario",
    pricing_title:"Planes simples y transparentes",
    pricing_sub:"Sin contratos. Cancela cuando quieras.",
    how_title:"¿Cómo funciona?", how_sub:"Sin instalación, sin registro, sin que tus archivos salgan de tu dispositivo.",
    how_steps:[["Elige tu herramienta","Selecciona la conversión que necesitas — PDF, Word, imágenes, Excel y más."],["Sube tu archivo","Arrastra el archivo o haz clic para seleccionarlo. Hasta 10 MB en el plan gratuito."],["Descarga el resultado","La conversión ocurre en tu navegador. Descarga el archivo en segundos."]],
    faq_title:"Preguntas frecuentes", faq:[
      ["¿Es completamente gratis?", "El plan gratuito incluye todas las herramientas sin registro, para archivos de hasta 10 MB y puedes unir hasta 2 PDFs a la vez. El plan Pro sube el límite a 200 MB y permite unir archivos ilimitados."],
      ["¿Mis archivos se suben a algún servidor?", "No. Todo ocurre en tu navegador con WebAssembly. Tus archivos nunca salen de tu dispositivo."],
      ["¿Qué formatos puedo convertir?", "PDF, Word (DOCX), Excel (XLSX), PowerPoint (PPTX), imágenes (JPG, PNG, WEBP). También puedes unir, dividir, comprimir, rotar u organizar PDFs."],
      ["¿Hay límite de tamaño?", "En el plan gratuito el límite es de 10 MB por archivo. Con Pro puedes convertir archivos de hasta 200 MB."],
      ["¿Funciona en móvil?", "Sí, en cualquier dispositivo con un navegador moderno: ordenador, tablet o móvil."],
      ["¿Puedo subir varios archivos a la vez?", "Para unir PDFs sí. El resto de herramientas procesan un archivo cada vez."],
      ["¿Funciona sin conexión a internet?", "Las conversiones que usan PDF, Word o imágenes funcionan completamente sin conexión una vez cargada la página. Solo las funciones de OCR y algunas externas requieren conexión."],
      ["¿Qué navegadores son compatibles?", "Chrome, Edge, Firefox y Safari en sus versiones de los últimos 2 años. Recomendamos Chrome o Edge para la mejor experiencia."],
      ["¿Puedo convertir PDFs protegidos con contraseña?", "morf puede eliminar restricciones de propietario (edición/impresión) con la herramienta 'Desbloquear PDF'. Los PDFs cifrados con contraseña de apertura no pueden procesarse."],
      ["¿Qué ocurre si la conversión falla?", "Recibirás un mensaje de error descriptivo. Las causas más comunes son archivos dañados, PDFs muy complejos o con fuentes incrustadas especiales. Si el problema persiste, escríbenos."]
    ],
    nav_privacy:"Privacidad", nav_api:"API", nav_help:"Ayuda",
    footer_copy:"morf · © 2026",
    footer_tools:"Herramientas populares", footer_company:"Empresa",
    search_ph:"Busca una herramienta…",
    cat_conv:"Conversión de documentos", cat_img:"Imágenes",
    cat_ops:"Operaciones PDF", cat_edit:"Edición PDF", cat_sec:"Seguridad y avanzado",
    stat_files:"archivos procesados", stat_speed:"velocidad media", stat_priv:"privado siempre",
    tools_more:"Ver todas las herramientas", tools_less:"Menos herramientas",
    plan_annual_total:"Facturado €53,88/año · ahorras €18",
    trust_browser:"100% en tu navegador", trust_noreg:"Sin registro", trust_free:"Gratis siempre",
    next_tool:"Prueba también",
    home_drop_title:"¿Qué quieres hacer?", home_drop_sub:"Elige una herramienta compatible con tu archivo",
    modal_contact:"Contacto", modal_api:"API de morf",
    err_title:"No se pudo completar la conversión",
    err_retry:"Reintentar",
    err_size:"El archivo supera el límite de 200 MB. Prueba con un archivo más pequeño.",
    err_protected:"El PDF está protegido con contraseña. Desprotégelo antes de convertir.",
    err_corrupt:"El archivo parece estar dañado o no es un formato válido.",
    err_range:"El rango de páginas no es válido. Usa el formato 1-3, 5, 7-9.",
    err_popup:"El navegador bloqueó la ventana emergente. Permite las ventanas emergentes e inténtalo de nuevo.",
    err_generic:"Ha ocurrido un error inesperado. Comprueba que el archivo no está dañado e inténtalo de nuevo.",
    err_suggest:"¿Sigue fallando? Escríbenos a hola@morf.app",
    err_odt:"Formato ODT detectado. Ábrelo en LibreOffice y guárdalo como .docx (Archivo → Guardar como → Word 2007-365) e inténtalo de nuevo.",
    watermark_label:"Texto de marca de agua",
    crop_label:"Márgenes a recortar (mm)",
    crop_top:"Arriba", crop_bottom:"Abajo", crop_left:"Izquierda", crop_right:"Derecha",
    sign_label:"Dibuja tu firma",
    sign_hint:"La firma se añadirá en la esquina inferior derecha de la última página.",
    // tools
    t:[ {label:"PDF → Word",        desc:"Convierte PDF a documento Word editable."},
        {label:"Word → PDF",        desc:"Transforma Word a PDF de alta fidelidad."},
        {label:"Imagen → PDF",      desc:"Agrupa JPG, PNG o WEBP en un único PDF."},
        {label:"Unir PDFs",         desc:"Fusiona varios PDFs respetando el orden."},
        {label:"Dividir PDF",       desc:"Extrae páginas o rangos de cualquier PDF."},
        {label:"Comprimir PDF",     desc:"Reduce el tamaño sin pérdida visible de calidad."},
        {label:"PNG → JPG",         desc:"Convierte imágenes PNG a formato JPG."},
        {label:"JPG → PNG",         desc:"Convierte imágenes JPG a formato PNG."},
        {label:"Rotar PDF",         desc:"Rota páginas de un PDF 90°, 180° o 270°."},
        {label:"Excel → PDF",       desc:"Convierte hojas de cálculo Excel a PDF."},
        {label:"PDF → PowerPoint",  desc:"Convierte cada página del PDF en una diapositiva PPTX.", popular:true},
        {label:"PDF → Excel",       desc:"Extrae el texto del PDF a una hoja de cálculo Excel.", popular:true},
        {label:"Marca de agua PDF", desc:"Añade un texto de marca de agua diagonal en todas las páginas."},
        {label:"Numerar páginas",   desc:"Inserta el número de página en el pie de cada hoja."},
        {label:"Recortar PDF",      desc:"Recorta los márgenes de todas las páginas del PDF."},
        {label:"PDF a grises",      desc:"Convierte el PDF a escala de grises."},
        {label:"Desbloquear PDF",   desc:"Elimina las restricciones de un PDF protegido."},
        {label:"Firmar PDF",        desc:"Dibuja tu firma y añádela a la última página."},
        {label:"OCR PDF",           desc:"Extrae el texto de PDFs escaneados con reconocimiento óptico.", pro:true},
        {label:"Proteger PDF",      desc:"Añade contraseña a un PDF para restringir el acceso.", comingSoon:true},
        {label:"PPTX → PDF",        desc:"Extrae el contenido de cada diapositiva PowerPoint a PDF."},
        {label:"PDF → Imágenes",    desc:"Exporta cada página del PDF como imagen PNG."},
        {label:"Organizar PDF",     desc:"Reordena o elimina páginas con arrastrar y soltar."},
        {label:"Borrar páginas",    desc:"Elimina páginas específicas de un PDF."},
        {label:"Reparar PDF",      desc:"Re-serializa el PDF para corregir errores de estructura."},
        {label:"HTML → PDF",       desc:"Abre tu archivo HTML en el navegador y lo convierte a PDF."},
        {label:"Aplanar PDF",      desc:"Convierte formularios rellenables en texto estático."},
        {label:"Anotar PDF",       desc:"Añade texto sobre cualquier página del PDF."},
        {label:"Redactar PDF",     desc:"Cubre zonas sensibles con rectángulos negros."},
        {label:"OCR Buscable",     desc:"Crea un PDF con capa de texto invisible para búsqueda con Ctrl+F."},
        {label:"Chat con PDF",     desc:"Chatea con el contenido del PDF usando inteligencia artificial."},
        {label:"Editor Visual",    desc:"Edita el PDF visualmente: añade texto y redacta zonas con clic."},
        {label:"PDF a Markdown",   desc:"Convierte el texto del PDF a formato Markdown listo para usar."},
        {label:"Resumir con IA",   desc:"Genera un resumen estructurado del PDF usando inteligencia artificial."},
        {label:"Comparar PDFs",    desc:"Compara dos PDFs y resalta las diferencias palabra a palabra."}],
    reconvert:"Repetir conversión",
    annot_add:"Añadir anotación de texto",
    annot_text:"Texto de la anotación…",
    annot_page:"Página",
    annot_size:"Tamaño",
    annot_add_btn:"+ Añadir",
    redact_add:"Añadir zona de redacción (en % del tamaño de página)",
    redact_add_btn:"+ Añadir zona",
    ocr_lang_label:"Idioma del documento",
    ocr_hint:"El OCR descargará los datos del idioma (~4 MB) la primera vez.",
    organize_hint:"Arrastra para reordenar · Clic en ✕ para eliminar",
    organize_empty:"No quedan páginas. Vuelve a subir el archivo.",
    del_pages_label:"Páginas a eliminar (ej. 1-3, 5, 7-9)",
    coming_soon_desc:"Estamos trabajando en esta herramienta. Estará disponible pronto.",
    coming_soon_toast:"¡Próximamente! Estamos trabajando en esta herramienta.",
    upgrade_pro_reason:"Esta herramienta es exclusiva del plan Pro.",
    share_hint:"¿Te ha sido útil? Comparte la herramienta",
    share_native:"Compartir",
    privacy_note:"Tu archivo nunca sale de tu navegador",
    // contact
    con_intro:"¿Tienes alguna duda o incidencia? Escríbenos y te respondemos en menos de 48h laborables.",
    con_name:"Nombre", con_email:"Email", con_subject:"Asunto", con_msg:"Mensaje",
    con_name_ph:"Tu nombre", con_email_ph:"tu@email.com", con_msg_ph:"Cuéntanos en detalle...",
    con_subjects:[["general","Consulta general"],["bug","Reportar un error"],["feature","Sugerencia"],["api","Acceso a la API"],["legal","Asunto legal"]],
    con_send:"Enviar mensaje", con_sending:"Enviando…", con_cancel:"Cancelar",
    con_done_title:"Mensaje recibido",
    con_done_sub:"Respondemos en menos de 48 horas en días laborables.",
    con_close:"Cerrar", con_required:"Rellena todos los campos",
    con_sent:"Mensaje enviado",
    con_resp_t:"Respuesta", con_resp_v:"< 48h laborables",
    // privacy
    priv_chips:["Sin seguimiento","Procesado local","Sin almacenamiento"],
    // api
    api_beta:"API en beta privada. Solicita acceso desde el formulario de contacto.",
    api_copy:"Copiar", api_copied:"✓ Copiado",
    api_plans:[{t:"Free",r:"50 req/mes",s:"10 MB",p:"Gratis"},{t:"Pro",r:"5.000 req/mes",s:"100 MB",p:"€19/mes"},{t:"Business",r:"Ilimitado",s:"500 MB",p:"€99/mes"}],
  },
  en: {
    code:"en", flag:"🇬🇧", name:"English",
    tagline:"No signup · No watermarks · 100% private",
    hero_h1a:"The fastest way to", hero_h1b:"convert your files.",
    hero_sub:"PDF, Word, Excel, images. Free for files up to 10 MB. Your files never leave your browser.",
    hero_cta:"Start for free",
    hero_drop:"Drop any file here",
    hero_drop_sub:"Automatic tool detection",
    tools_title:"Tools", tools_count:"available",
    detected:"Detected",
    unknown_fmt:"Format not recognised",
    incompat:"Incompatible format",
    drag_single:"Drop your file here",
    drag_multi:"Drop your files here",
    click_hint:"or click to browse",
    processing:"Processing…",
    convert:"Convert", cancel:"Cancel",
    download:"Download", other:"Convert another",
    done_title:"Ready to download",
    done_sub_s:"file processed", done_sub_p:"files processed",
    conv_done:"Conversion complete",
    dl_started:"Download started",
    pages_label:"Page range (e.g. 1-3, 5, 7-9)",
    pages_ph:"Empty = all pages",
    compress_level:"Compression level",
    q_low:"Light", q_med:"Medium", q_high:"Maximum",
    feat:[ ["Local processing","Your files never leave your browser."],
           ["Format preserved","Fonts, margins and tables intact."],
           ["Instant download","Result ready in seconds."],
           ["No ads","Free plan with no advertising."] ],
    max_size:"max. 200 MB",
    counter:"files converted",
    step_read:"Reading file…", step_proc:"Processing…", step_done:"Done!",
    free_limit:"File exceeds the 10 MB limit of the free plan.",
    free_batch:"The free plan allows merging up to 2 files. Upgrade to Pro to merge unlimited files.",
    free_size:"File exceeds the 10 MB limit of the free plan.",
    upgrade_cta:"See Pro plans",
    upgrade_sub:"Unlimited · Files up to 200 MB · No ads",
    plan_free:"Free", plan_pro:"Pro",
    plan_free_desc:"For occasional use",
    plan_pro_desc:"For professional use",
    plan_monthly:"per month", plan_yearly:"per year",
    plan_save:"Save 25%",
    plan_cta_free:"Start for free",
    plan_cta_pro:"Start with Pro",
    plan_current:"Current plan",
    feat_batch:"Merge up to 2 files",
    merge_hint:"Free plan: max. 2 files. Upgrade to Pro for more.",
    feat_size_free:"Files up to 10 MB",
    feat_size_pro:"Files up to 200 MB",
    feat_tools:"All tools included",
    feat_unlimited:"Merge unlimited files",
    feat_noad:"No ads",
    feat_priority:"Priority processing",
    pricing_title:"Simple, transparent pricing",
    pricing_sub:"No contracts. Cancel anytime.",
    how_title:"How it works", how_sub:"No installation, no sign-up, your files never leave your device.",
    how_steps:[["Choose your tool","Select the conversion you need — PDF, Word, images, Excel and more."],["Upload your file","Drag the file or click to select it. Up to 10 MB on the free plan."],["Download the result","Conversion happens in your browser. Download the file in seconds."]],
    faq_title:"Frequently asked questions", faq:[
      ["Is it completely free?", "The free plan includes all tools with no sign-up, for files up to 10 MB and merging up to 2 PDFs at once. Pro raises the limit to 200 MB and allows unlimited merging."],
      ["Are my files uploaded to a server?", "No. Everything runs in your browser via WebAssembly. Your files never leave your device."],
      ["What formats can I convert?", "PDF, Word (DOCX), Excel (XLSX), PowerPoint (PPTX), images (JPG, PNG, WEBP). Also merge, split, compress, rotate or organise PDFs."],
      ["Is there a file size limit?", "On the free plan the limit is 10 MB per file. With Pro you can convert files up to 200 MB."],
      ["Does it work on mobile?", "Yes, on any device with a modern browser: desktop, tablet or mobile."],
      ["Can I upload multiple files at once?", "For merging PDFs yes. Other tools process one file at a time."],
      ["Does it work offline?", "PDF, Word and image conversions work fully offline once the page is loaded. OCR and some external features require an internet connection."],
      ["Which browsers are supported?", "Chrome, Edge, Firefox and Safari (last 2 major versions). Chrome or Edge are recommended for the best experience."],
      ["Can I convert password-protected PDFs?", "morf can remove owner restrictions (editing/printing) using the Unlock PDF tool. PDFs encrypted with an open password cannot be processed."],
      ["What happens if conversion fails?", "You will see a descriptive error message. Common causes are corrupted files, very complex PDFs or embedded special fonts. If the issue persists, contact us."]
    ],
    hist_title:"Recent conversions", hist_empty:"You haven't converted any files yet.", hist_clear:"Clear history",
    nav_privacy:"Privacy", nav_api:"API", nav_help:"Help",
    footer_copy:"morf · © 2026",
    footer_tools:"Popular tools", footer_company:"Company",
    search_ph:"Search a tool…",
    cat_conv:"Document conversion", cat_img:"Images",
    cat_ops:"PDF operations", cat_edit:"PDF editing", cat_sec:"Security & advanced",
    stat_files:"files converted", stat_speed:"average speed", stat_priv:"always private",
    tools_more:"View all tools", tools_less:"Show less",
    plan_annual_total:"Billed €53.88/year · save €18",
    trust_browser:"100% in your browser", trust_noreg:"No sign-up", trust_free:"Always free",
    next_tool:"Try also",
    home_drop_title:"What do you want to do?", home_drop_sub:"Choose a tool compatible with your file",
    modal_contact:"Contact", modal_api:"morf API",
    err_title:"Conversion failed",
    err_retry:"Try again",
    err_size:"File exceeds the 200 MB limit. Please use a smaller file.",
    err_protected:"This PDF is password-protected. Remove the password before converting.",
    err_corrupt:"The file appears to be corrupted or is not a valid format.",
    err_range:"Invalid page range. Use the format 1-3, 5, 7-9.",
    err_popup:"The browser blocked the pop-up window. Allow pop-ups for this site and try again.",
    err_generic:"An unexpected error occurred. Check the file is not corrupted and try again.",
    err_suggest:"Still not working? Email us at hola@morf.app",
    err_odt:"ODT format detected. Open it in LibreOffice and save as .docx (File → Save As → Word 2007-365) then try again.",
    watermark_label:"Watermark text",
    crop_label:"Margins to crop (mm)",
    crop_top:"Top", crop_bottom:"Bottom", crop_left:"Left", crop_right:"Right",
    sign_label:"Draw your signature",
    sign_hint:"The signature will be placed at the bottom-right corner of the last page.",
    t:[ {label:"PDF → Word",        desc:"Convert PDF to an editable Word document."},
        {label:"Word → PDF",        desc:"Turn Word documents into high-fidelity PDFs."},
        {label:"Image → PDF",       desc:"Bundle JPG, PNG or WEBP files into one PDF."},
        {label:"Merge PDFs",        desc:"Combine multiple PDFs keeping the order."},
        {label:"Split PDF",         desc:"Extract pages or ranges from any PDF."},
        {label:"Compress PDF",      desc:"Reduce file size with no visible quality loss."},
        {label:"PNG → JPG",         desc:"Convert PNG images to JPG format."},
        {label:"JPG → PNG",         desc:"Convert JPG images to PNG format."},
        {label:"Rotate PDF",        desc:"Rotate PDF pages 90°, 180° or 270°."},
        {label:"Excel → PDF",       desc:"Convert Excel spreadsheets to PDF."},
        {label:"PDF → PowerPoint",  desc:"Convert each PDF page into a PowerPoint slide.", popular:true},
        {label:"PDF → Excel",       desc:"Extract PDF text into an Excel spreadsheet.", popular:true},
        {label:"Watermark PDF",     desc:"Add a diagonal watermark text to all pages."},
        {label:"Number Pages",      desc:"Insert page numbers at the bottom of each page."},
        {label:"Crop PDF",          desc:"Crop the margins from all pages of a PDF."},
        {label:"PDF to Greyscale",  desc:"Convert a PDF to greyscale."},
        {label:"Unlock PDF",        desc:"Remove restrictions from a protected PDF."},
        {label:"Sign PDF",          desc:"Draw your signature and add it to the last page."},
        {label:"OCR PDF",           desc:"Extract text from scanned PDFs using optical character recognition.", pro:true},
        {label:"Protect PDF",       desc:"Add a password to a PDF to restrict access.", comingSoon:true},
        {label:"PPTX → PDF",        desc:"Extract each PowerPoint slide's content to PDF."},
        {label:"PDF → Images",      desc:"Export each PDF page as a PNG image."},
        {label:"Organise PDF",      desc:"Reorder or delete pages using drag and drop."},
        {label:"Delete pages",      desc:"Remove specific pages from a PDF."},
        {label:"Repair PDF",        desc:"Re-serialises the PDF to fix structural errors."},
        {label:"HTML → PDF",        desc:"Opens your HTML file in the browser and converts it to PDF."},
        {label:"Flatten PDF",       desc:"Converts fillable form fields into static text."},
        {label:"Annotate PDF",      desc:"Add text overlays to any page of a PDF."},
        {label:"Redact PDF",        desc:"Cover sensitive areas with black rectangles."},
        {label:"Searchable OCR",    desc:"Creates a PDF with an invisible text layer for Ctrl+F search."},
        {label:"Chat with PDF",     desc:"Chat with your PDF content using artificial intelligence."},
        {label:"Visual Editor",     desc:"Visually edit the PDF: add text and redact areas with a click."},
        {label:"PDF to Markdown",   desc:"Converts PDF text to Markdown format ready to use."},
        {label:"AI Summarize",      desc:"Generates a structured summary of the PDF using artificial intelligence."},
        {label:"Compare PDFs",      desc:"Compare two PDFs and highlight differences word by word."} ],
    reconvert:"Convert again",
    annot_add:"Add text annotation",
    annot_text:"Annotation text…",
    annot_page:"Page",
    annot_size:"Size",
    annot_add_btn:"+ Add",
    redact_add:"Add redaction zone (as % of page size)",
    redact_add_btn:"+ Add zone",
    ocr_lang_label:"Document language",
    ocr_hint:"OCR will download language data (~4 MB) on first use.",
    organize_hint:"Drag to reorder · Click ✕ to remove",
    organize_empty:"No pages remaining. Re-upload the file.",
    del_pages_label:"Pages to delete (e.g. 1-3, 5, 7-9)",
    coming_soon_desc:"We are working on this tool. It will be available soon.",
    coming_soon_toast:"Coming soon! We are working on this tool.",
    upgrade_pro_reason:"This tool is exclusive to the Pro plan.",
    share_hint:"Was it helpful? Share this tool",
    share_native:"Share",
    privacy_note:"Your file never leaves your browser",
    con_intro:"Got a question or issue? Write to us and we'll reply within 48 business hours.",
    con_name:"Name", con_email:"Email", con_subject:"Subject", con_msg:"Message",
    con_name_ph:"Your name", con_email_ph:"you@email.com", con_msg_ph:"Tell us in detail...",
    con_subjects:[["general","General enquiry"],["bug","Report a bug"],["feature","Feature request"],["api","API access"],["legal","Legal matter"]],
    con_send:"Send message", con_sending:"Sending…", con_cancel:"Cancel",
    con_done_title:"Message received",
    con_done_sub:"We reply within 48 business hours. Check your spam folder just in case.",
    con_close:"Close", con_required:"Please fill in all fields",
    con_sent:"Message sent",
    con_resp_t:"Response time", con_resp_v:"< 48 business hours",
    priv_chips:["No tracking","Local processing","No storage"],
    api_beta:"API is in private beta. Request access from the contact form.",
    api_copy:"Copy", api_copied:"✓ Copied",
    api_plans:[{t:"Free",r:"50 req/mo",s:"10 MB",p:"Free"},{t:"Pro",r:"5,000 req/mo",s:"100 MB",p:"€19/mo"},{t:"Business",r:"Unlimited",s:"500 MB",p:"€99/mo"}],
  },
  fr: {
    code:"fr", flag:"🇫🇷", name:"Français",
    tagline:"Sans inscription · Sans filigrane · 100% privé",
    hero_h1a:"La façon la plus rapide de", hero_h1b:"convertir vos fichiers.",
    hero_sub:"PDF, Word, Excel, images. Gratuit pour les fichiers jusqu'à 10 Mo. Vos fichiers restent dans votre navigateur.",
    hero_cta:"Commencer gratuitement",
    hero_drop:"Déposez n'importe quel fichier ici",
    hero_drop_sub:"Détection automatique de l'outil",
    tools_title:"Outils", tools_count:"disponibles",
    detected:"Détecté",
    unknown_fmt:"Format non reconnu",
    incompat:"Format incompatible",
    drag_single:"Déposez votre fichier ici",
    drag_multi:"Déposez vos fichiers ici",
    click_hint:"ou cliquez pour parcourir",
    processing:"Traitement…",
    convert:"Convertir", cancel:"Annuler",
    download:"Télécharger", other:"Autre fichier",
    done_title:"Prêt à télécharger",
    done_sub_s:"fichier traité", done_sub_p:"fichiers traités",
    conv_done:"Conversion terminée",
    dl_started:"Téléchargement démarré",
    pages_label:"Plage de pages (ex : 1-3, 5, 7-9)",
    pages_ph:"Vide = toutes les pages",
    compress_level:"Niveau de compression",
    q_low:"Légère", q_med:"Moyenne", q_high:"Maximum",
    feat:[ ["Traitement local","Vos fichiers ne quittent pas le navigateur."],
           ["Format conservé","Polices, marges et tableaux intacts."],
           ["Téléchargement immédiat","Résultat prêt en quelques secondes."],
           ["Sans publicité","Plan gratuit sans aucune publicité."] ],
    max_size:"max. 200 Mo",
    counter:"fichiers convertis",
    free_limit:"Le fichier dépasse la limite de 10 Mo du plan gratuit.",
    free_batch:"Le plan gratuit permet de fusionner jusqu'à 2 fichiers. Passez à Pro pour en fusionner autant que vous voulez.",
    free_size:"Le fichier dépasse la limite de 10 Mo du plan gratuit.",
    upgrade_cta:"Voir les plans Pro",
    upgrade_sub:"Illimité · Fichiers jusqu'à 200 Mo · Sans pub",
    plan_free:"Gratuit", plan_pro:"Pro",
    plan_free_desc:"Pour usage occasionnel",
    plan_pro_desc:"Pour usage professionnel",
    plan_monthly:"par mois", plan_yearly:"par an",
    plan_save:"Économisez 25%",
    plan_cta_free:"Commencer gratuitement",
    plan_cta_pro:"Commencer avec Pro",
    plan_current:"Plan actuel",
    feat_batch:"Fusionner jusqu'à 2 fichiers",
    merge_hint:"Plan gratuit: max. 2 fichiers. Passez à Pro pour plus.",
    feat_size_free:"Fichiers jusqu'à 10 Mo",
    feat_size_pro:"Fichiers jusqu'à 200 Mo",
    feat_tools:"Tous les outils inclus",
    feat_unlimited:"Fusion illimitée de fichiers",
    feat_noad:"Sans publicité",
    feat_priority:"Traitement prioritaire",
    pricing_title:"Tarifs simples et transparents",
    pricing_sub:"Sans engagement. Annulez à tout moment.",
    how_title:"Comment ça marche ?", how_sub:"Sans installation, sans inscription, vos fichiers ne quittent pas votre appareil.",
    how_steps:[["Choisissez votre outil","Sélectionnez la conversion dont vous avez besoin — PDF, Word, images, Excel et plus."],["Importez votre fichier","Glissez le fichier ou cliquez pour le sélectionner. Jusqu'à 10 Mo en plan gratuit."],["Téléchargez le résultat","La conversion se fait dans votre navigateur. Téléchargez le fichier en quelques secondes."]],
    faq_title:"Questions fréquentes", faq:[
      ["Est-ce entièrement gratuit ?", "Le plan gratuit inclut tous les outils sans inscription, pour les fichiers jusqu'à 10 Mo et la fusion jusqu'à 2 PDFs. Pro monte la limite à 200 Mo et permet la fusion illimitée."],
      ["Mes fichiers sont-ils envoyés à un serveur ?", "Non. Tout se passe dans votre navigateur via WebAssembly. Vos fichiers ne quittent jamais votre appareil."],
      ["Quels formats puis-je convertir ?", "PDF, Word (DOCX), Excel (XLSX), PowerPoint (PPTX), images (JPG, PNG, WEBP). Fusionnez, divisez, compressez, faites pivoter ou organisez des PDFs."],
      ["Y a-t-il une limite de taille ?", "En plan gratuit, la limite est de 10 Mo par fichier. Avec Pro, vous pouvez convertir des fichiers jusqu'à 200 Mo."],
      ["Fonctionne-t-il sur mobile ?", "Oui, sur tout appareil avec un navigateur moderne : ordinateur, tablette ou mobile."],
      ["Puis-je uploader plusieurs fichiers à la fois ?", "Pour fusionner des PDFs oui. Les autres outils traitent un fichier à la fois."],
      ["Fonctionne-t-il hors ligne ?", "Les conversions PDF, Word et images fonctionnent entièrement hors ligne une fois la page chargée. L'OCR et certaines fonctions externes nécessitent une connexion."],
      ["Quels navigateurs sont compatibles ?", "Chrome, Edge, Firefox et Safari (2 dernières versions majeures). Chrome ou Edge sont recommandés pour la meilleure expérience."],
      ["Puis-je convertir des PDFs protégés par mot de passe ?", "morf peut supprimer les restrictions propriétaire (édition/impression) avec l'outil 'Déverrouiller PDF'. Les PDFs chiffrés avec un mot de passe d'ouverture ne peuvent pas être traités."],
      ["Que se passe-t-il si la conversion échoue ?", "Un message d'erreur descriptif s'affichera. Les causes les plus fréquentes sont les fichiers corrompus ou les PDFs très complexes. Si le problème persiste, contactez-nous."]
    ],
    step_read:"Lecture du fichier…", step_proc:"Traitement…", step_done:"Terminé !",
    hist_title:"Conversions récentes", hist_empty:"Vous n'avez pas encore converti de fichiers.", hist_clear:"Effacer l'historique",
    nav_privacy:"Confidentialité", nav_api:"API", nav_help:"Aide",
    footer_copy:"morf · © 2026",
    footer_tools:"Outils populaires", footer_company:"Entreprise",
    search_ph:"Rechercher un outil…",
    cat_conv:"Conversion de documents", cat_img:"Images",
    cat_ops:"Opérations PDF", cat_edit:"Édition PDF", cat_sec:"Sécurité et avancé",
    stat_files:"fichiers convertis", stat_speed:"vitesse moyenne", stat_priv:"toujours privé",
    tools_more:"Voir tous les outils", tools_less:"Moins d'outils",
    plan_annual_total:"Facturé 53,88 €/an · économisez 18 €",
    trust_browser:"100% dans votre navigateur", trust_noreg:"Sans inscription", trust_free:"Toujours gratuit",
    next_tool:"Essayez aussi",
    home_drop_title:"Que voulez-vous faire ?", home_drop_sub:"Choisissez un outil compatible avec votre fichier",
    modal_contact:"Contact", modal_api:"API morf",
    err_title:"La conversion a échoué",
    err_retry:"Réessayer",
    err_size:"Le fichier dépasse la limite de 200 Mo. Essayez avec un fichier plus petit.",
    err_protected:"Ce PDF est protégé par un mot de passe. Supprimez-le avant de convertir.",
    err_corrupt:"Le fichier semble corrompu ou n'est pas dans un format valide.",
    err_range:"Plage de pages invalide. Utilisez le format 1-3, 5, 7-9.",
    err_popup:"Le navigateur a bloqué la fenêtre contextuelle. Autorisez les popups et réessayez.",
    err_generic:"Une erreur inattendue s'est produite. Vérifiez que le fichier n'est pas corrompu.",
    err_suggest:"Toujours un problème ? Écrivez-nous à hola@morf.app",
    err_odt:"Format ODT détecté. Ouvrez-le dans LibreOffice et enregistrez-le en .docx (Fichier → Enregistrer sous → Word 2007-365) puis réessayez.",
    watermark_label:"Texte du filigrane",
    crop_label:"Marges à rogner (mm)",
    crop_top:"Haut", crop_bottom:"Bas", crop_left:"Gauche", crop_right:"Droite",
    sign_label:"Dessinez votre signature",
    sign_hint:"La signature sera placée en bas à droite de la dernière page.",
    t:[ {label:"PDF → Word",         desc:"Convertit un PDF en document Word éditable."},
        {label:"Word → PDF",         desc:"Transforme Word en PDF haute fidélité."},
        {label:"Image → PDF",        desc:"Regroupe JPG, PNG ou WEBP en un seul PDF."},
        {label:"Fusionner PDFs",     desc:"Combine plusieurs PDFs en respectant l'ordre."},
        {label:"Diviser PDF",        desc:"Extrait des pages ou plages de n'importe quel PDF."},
        {label:"Compresser PDF",     desc:"Réduit la taille sans perte visible de qualité."},
        {label:"PNG → JPG",          desc:"Convertit des images PNG en format JPG."},
        {label:"JPG → PNG",          desc:"Convertit des images JPG en format PNG."},
        {label:"Rotation PDF",       desc:"Fait pivoter les pages PDF de 90°, 180° ou 270°."},
        {label:"Excel → PDF",        desc:"Convertit des feuilles Excel en PDF."},
        {label:"PDF → PowerPoint",   desc:"Convertit chaque page PDF en diapositive PPTX.", popular:true},
        {label:"PDF → Excel",        desc:"Extrait le texte du PDF dans un tableur Excel.", popular:true},
        {label:"Filigrane PDF",      desc:"Ajoute un filigrane diagonal sur toutes les pages."},
        {label:"Numéroter pages",    desc:"Insère le numéro de page en bas de chaque feuille."},
        {label:"Rogner PDF",         desc:"Rogne les marges de toutes les pages du PDF."},
        {label:"PDF en niveaux gris",desc:"Convertit le PDF en niveaux de gris."},
        {label:"Déverrouiller PDF",  desc:"Supprime les restrictions d'un PDF protégé."},
        {label:"Signer PDF",         desc:"Dessinez votre signature et ajoutez-la à la dernière page."},
        {label:"OCR PDF",            desc:"Extrait le texte des PDFs numérisés par reconnaissance optique.", pro:true},
        {label:"Protéger PDF",        desc:"Ajoutez un mot de passe à un PDF pour restreindre l'accès.", comingSoon:true},
        {label:"PPTX → PDF",         desc:"Extrait le contenu de chaque diapositive PowerPoint en PDF."},
        {label:"PDF → Images",       desc:"Exporte chaque page du PDF en image PNG."},
        {label:"Organiser PDF",      desc:"Réorganisez ou supprimez des pages par glisser-déposer."},
        {label:"Supprimer des pages",desc:"Supprimez des pages spécifiques d'un PDF."},
        {label:"Réparer PDF",        desc:"Re-sérialise le PDF pour corriger les erreurs de structure."},
        {label:"HTML → PDF",         desc:"Ouvre votre fichier HTML dans le navigateur et le convertit en PDF."},
        {label:"Aplatir PDF",        desc:"Convertit les champs de formulaire en texte statique."},
        {label:"Annoter PDF",        desc:"Ajoutez du texte sur n'importe quelle page d'un PDF."},
        {label:"Rédiger PDF",        desc:"Couvrez les zones sensibles avec des rectangles noirs."},
        {label:"OCR Recherchable",   desc:"Crée un PDF avec couche de texte invisible pour la recherche Ctrl+F."},
        {label:"Chat avec PDF",      desc:"Discutez avec le contenu de votre PDF grâce à l'intelligence artificielle."},
        {label:"Éditeur Visuel",     desc:"Éditez le PDF visuellement : ajoutez du texte et rédigez des zones en un clic."},
        {label:"PDF en Markdown",    desc:"Convertit le texte du PDF au format Markdown prêt à l'emploi."},
        {label:"Résumer avec IA",    desc:"Génère un résumé structuré du PDF grâce à l'intelligence artificielle."},
        {label:"Comparer PDFs",      desc:"Compare deux PDFs et met en évidence les différences mot par mot."} ],
    reconvert:"Convertir à nouveau",
    annot_add:"Ajouter une annotation de texte",
    annot_text:"Texte de l'annotation…",
    annot_page:"Page",
    annot_size:"Taille",
    annot_add_btn:"+ Ajouter",
    redact_add:"Ajouter une zone de rédaction (en % de la taille de la page)",
    redact_add_btn:"+ Ajouter une zone",
    ocr_lang_label:"Langue du document",
    ocr_hint:"L'OCR téléchargera les données de langue (~4 Mo) lors de la première utilisation.",
    organize_hint:"Glisser pour réorganiser · Clic ✕ pour supprimer",
    organize_empty:"Plus de pages restantes. Ré-importez le fichier.",
    del_pages_label:"Pages à supprimer (ex. 1-3, 5, 7-9)",
    coming_soon_desc:"Nous travaillons sur cet outil. Il sera disponible prochainement.",
    coming_soon_toast:"Bientôt disponible ! Nous travaillons sur cet outil.",
    upgrade_pro_reason:"Cet outil est exclusif au plan Pro.",
    share_hint:"Utile ? Partagez cet outil",
    share_native:"Partager",
    privacy_note:"Votre fichier ne quitte jamais votre navigateur",
    con_intro:"Une question ou un problème ? Écrivez-nous et nous répondons en moins de 48h ouvrées.",
    con_name:"Nom", con_email:"E-mail", con_subject:"Sujet", con_msg:"Message",
    con_name_ph:"Votre nom", con_email_ph:"vous@email.com", con_msg_ph:"Décrivez en détail...",
    con_subjects:[["general","Demande générale"],["bug","Signaler un bug"],["feature","Suggestion"],["api","Accès API"],["legal","Question légale"]],
    con_send:"Envoyer", con_sending:"Envoi…", con_cancel:"Annuler",
    con_done_title:"Message reçu",
    con_done_sub:"Nous répondons dans les 48 heures ouvrées.",
    con_close:"Fermer", con_required:"Veuillez remplir tous les champs",
    con_sent:"Message envoyé",
    con_resp_t:"Délai de réponse", con_resp_v:"< 48h ouvrées",
    priv_chips:["Sans suivi","Traitement local","Sans stockage"],
    api_beta:"API en bêta privée. Demandez l'accès via le formulaire de contact.",
    api_copy:"Copier", api_copied:"✓ Copié",
    api_plans:[{t:"Free",r:"50 req/mois",s:"10 Mo",p:"Gratuit"},{t:"Pro",r:"5 000 req/mois",s:"100 Mo",p:"€19/mois"},{t:"Business",r:"Illimité",s:"500 Mo",p:"€99/mois"}],
  },
  de: {
    code:"de", flag:"🇩🇪", name:"Deutsch",
    tagline:"Ohne Anmeldung · Kein Wasserzeichen · 100% privat",
    hero_h1a:"Der schnellste Weg,", hero_h1b:"deine Dateien zu konvertieren.",
    hero_sub:"PDF, Word, Excel, Bilder. Kostenlos für Dateien bis 10 MB. Deine Dateien verlassen den Browser nicht.",
    hero_cta:"Kostenlos starten",
    hero_drop:"Datei hier ablegen",
    hero_drop_sub:"Automatische Tool-Erkennung",
    tools_title:"Werkzeuge", tools_count:"verfügbar",
    detected:"Erkannt",
    unknown_fmt:"Format nicht erkannt",
    incompat:"Inkompatibles Format",
    drag_single:"Datei hier ablegen",
    drag_multi:"Dateien hier ablegen",
    click_hint:"oder klicken zum Auswählen",
    processing:"Verarbeitung…",
    convert:"Konvertieren", cancel:"Abbrechen",
    download:"Herunterladen", other:"Weitere Datei",
    done_title:"Bereit zum Herunterladen",
    done_sub_s:"Datei verarbeitet", done_sub_p:"Dateien verarbeitet",
    conv_done:"Konvertierung abgeschlossen",
    dl_started:"Download gestartet",
    pages_label:"Seitenbereich (z. B. 1-3, 5, 7-9)",
    pages_ph:"Leer = alle Seiten",
    compress_level:"Komprimierungsgrad",
    q_low:"Leicht", q_med:"Mittel", q_high:"Maximum",
    feat:[ ["Lokale Verarbeitung","Deine Dateien verlassen den Browser nicht."],
           ["Format erhalten","Schriften, Ränder und Tabellen intakt."],
           ["Sofort-Download","Ergebnis in Sekunden bereit."],
           ["Keine Werbung","Kostenloser Plan ohne Werbung."] ],
    max_size:"max. 200 MB",
    free_limit:"Die Datei überschreitet das 10-MB-Limit des kostenlosen Plans.",
    free_batch:"Im kostenlosen Plan können bis zu 2 Dateien zusammengeführt werden. Upgrade auf Pro für unbegrenzte Dateien.",
    free_size:"Die Datei überschreitet das 10-MB-Limit des kostenlosen Plans.",
    upgrade_cta:"Pro-Pläne ansehen",
    upgrade_sub:"Unbegrenzt · Dateien bis 200 MB · Keine Werbung",
    plan_free:"Kostenlos", plan_pro:"Pro",
    plan_free_desc:"Für gelegentliche Nutzung",
    plan_pro_desc:"Für professionelle Nutzung",
    plan_monthly:"pro Monat", plan_yearly:"pro Jahr",
    plan_save:"25% sparen",
    plan_cta_free:"Kostenlos starten",
    plan_cta_pro:"Mit Pro starten",
    plan_current:"Aktueller Plan",
    feat_batch:"Bis zu 2 Dateien zusammenführen",
    merge_hint:"Kostenloser Plan: max. 2 Dateien. Upgrade auf Pro für mehr.",
    feat_size_free:"Dateien bis 10 MB",
    feat_size_pro:"Dateien bis 200 MB",
    feat_tools:"Alle Tools inklusive",
    feat_unlimited:"Unbegrenzte Dateien zusammenführen",
    feat_noad:"Keine Werbung",
    feat_priority:"Prioritätsverarbeitung",
    pricing_title:"Einfache, transparente Preise",
    pricing_sub:"Keine Verträge. Jederzeit kündbar.",
    how_title:"Wie funktioniert es?", how_sub:"Keine Installation, keine Anmeldung, deine Dateien verlassen dein Gerät nicht.",
    how_steps:[["Wähle dein Tool","Wähle die gewünschte Konvertierung — PDF, Word, Bilder, Excel und mehr."],["Lade deine Datei hoch","Ziehe die Datei oder klicke zur Auswahl. Bis zu 10 MB im kostenlosen Plan."],["Lade das Ergebnis herunter","Die Konvertierung erfolgt in deinem Browser. Datei in Sekunden herunterladen."]],
    faq_title:"Häufig gestellte Fragen", faq:[
      ["Ist es komplett kostenlos?", "Der kostenlose Plan umfasst alle Tools ohne Anmeldung, für Dateien bis 10 MB und das Zusammenführen von bis zu 2 PDFs. Pro erhöht das Limit auf 200 MB und erlaubt unbegrenzte Zusammenführung."],
      ["Werden meine Dateien hochgeladen?", "Nein. Alles läuft im Browser via WebAssembly. Deine Dateien verlassen niemals dein Gerät."],
      ["Welche Formate kann ich konvertieren?", "PDF, Word (DOCX), Excel (XLSX), PowerPoint (PPTX), Bilder (JPG, PNG, WEBP). PDFs zusammenführen, teilen, komprimieren, drehen oder organisieren."],
      ["Gibt es ein Dateigrößenlimit?", "Im kostenlosen Plan liegt das Limit bei 10 MB pro Datei. Mit Pro kannst du Dateien bis zu 200 MB konvertieren."],
      ["Funktioniert es auf dem Handy?", "Ja, auf jedem Gerät mit einem modernen Browser: Desktop, Tablet oder Handy."],
      ["Kann ich mehrere Dateien gleichzeitig hochladen?", "Beim Zusammenführen von PDFs ja. Andere Tools verarbeiten eine Datei pro Mal."],
      ["Funktioniert es offline?", "PDF-, Word- und Bildkonvertierungen funktionieren vollständig offline, sobald die Seite geladen ist. OCR und einige externe Funktionen erfordern eine Internetverbindung."],
      ["Welche Browser werden unterstützt?", "Chrome, Edge, Firefox und Safari (letzte 2 Hauptversionen). Chrome oder Edge werden für die beste Erfahrung empfohlen."],
      ["Kann ich passwortgeschützte PDFs konvertieren?", "morf kann Eigentümerbeschränkungen (Bearbeitung/Druck) mit dem Tool 'PDF entsperren' entfernen. PDFs, die mit einem Öffnungspasswort verschlüsselt sind, können nicht verarbeitet werden."],
      ["Was passiert, wenn die Konvertierung fehlschlägt?", "Du erhältst eine beschreibende Fehlermeldung. Häufige Ursachen sind beschädigte Dateien oder sehr komplexe PDFs. Wenn das Problem weiterhin besteht, kontaktiere uns."]
    ],
    counter:"Dateien konvertiert",
    step_read:"Datei lesen…", step_proc:"Verarbeitung…", step_done:"Fertig!",
    hist_title:"Letzte Konvertierungen", hist_empty:"Du hast noch keine Dateien konvertiert.", hist_clear:"Verlauf löschen",
    nav_privacy:"Datenschutz", nav_api:"API", nav_help:"Hilfe",
    footer_copy:"morf · © 2026",
    footer_tools:"Beliebte Tools", footer_company:"Unternehmen",
    search_ph:"Tool suchen…",
    cat_conv:"Dokumentkonvertierung", cat_img:"Bilder",
    cat_ops:"PDF-Operationen", cat_edit:"PDF-Bearbeitung", cat_sec:"Sicherheit & Erweitert",
    stat_files:"konvertierte Dateien", stat_speed:"Durchschnittsgeschwindigkeit", stat_priv:"immer privat",
    tools_more:"Alle Tools anzeigen", tools_less:"Weniger anzeigen",
    plan_annual_total:"53,88 €/Jahr abgerechnet · spare 18 €",
    trust_browser:"100% im Browser", trust_noreg:"Keine Anmeldung", trust_free:"Immer kostenlos",
    next_tool:"Probiere auch",
    home_drop_title:"Was möchtest du tun?", home_drop_sub:"Wähle ein Tool, das mit deiner Datei kompatibel ist",
    modal_contact:"Kontakt", modal_api:"morf API",
    err_title:"Konvertierung fehlgeschlagen",
    err_retry:"Erneut versuchen",
    err_size:"Die Datei überschreitet das 200-MB-Limit. Bitte verwende eine kleinere Datei.",
    err_protected:"Dieses PDF ist passwortgeschützt. Entferne das Passwort vor der Konvertierung.",
    err_corrupt:"Die Datei scheint beschädigt oder kein gültiges Format zu sein.",
    err_range:"Ungültiger Seitenbereich. Verwende das Format 1-3, 5, 7-9.",
    err_popup:"Der Browser hat das Popup-Fenster blockiert. Erlaube Popups und versuche es erneut.",
    err_generic:"Ein unerwarteter Fehler ist aufgetreten. Prüfe, ob die Datei nicht beschädigt ist.",
    err_suggest:"Immer noch Probleme? Schreib uns an hola@morf.app",
    err_odt:"ODT-Format erkannt. Öffne es in LibreOffice und speichere es als .docx (Datei → Speichern unter → Word 2007-365) und versuche es erneut.",
    watermark_label:"Wasserzeichen-Text",
    crop_label:"Zu beschneidende Ränder (mm)",
    crop_top:"Oben", crop_bottom:"Unten", crop_left:"Links", crop_right:"Rechts",
    sign_label:"Unterschrift zeichnen",
    sign_hint:"Die Unterschrift wird unten rechts auf der letzten Seite platziert.",
    t:[ {label:"PDF → Word",            desc:"Konvertiert PDF in ein bearbeitbares Word-Dokument."},
        {label:"Word → PDF",            desc:"Wandelt Word in hochwertige PDFs um."},
        {label:"Bild → PDF",            desc:"Fasst JPG, PNG oder WEBP in eine PDF zusammen."},
        {label:"PDFs zusammenführen",   desc:"Kombiniert mehrere PDFs in der richtigen Reihenfolge."},
        {label:"PDF teilen",            desc:"Extrahiert Seiten oder Bereiche aus beliebigen PDFs."},
        {label:"PDF komprimieren",      desc:"Reduziert die Dateigröße ohne sichtbaren Qualitätsverlust."},
        {label:"PNG → JPG",             desc:"Konvertiert PNG-Bilder in das JPG-Format."},
        {label:"JPG → PNG",             desc:"Konvertiert JPG-Bilder in das PNG-Format."},
        {label:"PDF drehen",            desc:"Dreht PDF-Seiten um 90°, 180° oder 270°."},
        {label:"Excel → PDF",           desc:"Konvertiert Excel-Tabellen in PDF."},
        {label:"PDF → PowerPoint",      desc:"Konvertiert jede PDF-Seite in eine PowerPoint-Folie.", popular:true},
        {label:"PDF → Excel",           desc:"Extrahiert PDF-Text in eine Excel-Tabelle.", popular:true},
        {label:"Wasserzeichen PDF",     desc:"Fügt diagonalen Wasserzeichentext auf allen Seiten ein."},
        {label:"Seiten nummerieren",    desc:"Fügt Seitenzahlen unten auf jeder Seite ein."},
        {label:"PDF zuschneiden",       desc:"Beschneidet die Ränder aller PDF-Seiten."},
        {label:"PDF in Graustufen",     desc:"Konvertiert das PDF in Graustufen."},
        {label:"PDF entsperren",        desc:"Entfernt Einschränkungen aus einem geschützten PDF."},
        {label:"PDF signieren",         desc:"Zeichnen Sie Ihre Unterschrift und fügen Sie sie der letzten Seite hinzu."},
        {label:"OCR PDF",               desc:"Text aus gescannten PDFs per optischer Zeichenerkennung extrahieren.", pro:true},
        {label:"PDF schützen",           desc:"Fügt ein Passwort zu einem PDF hinzu, um den Zugriff zu beschränken.", comingSoon:true},
        {label:"PPTX → PDF",            desc:"Extrahiert den Inhalt jeder PowerPoint-Folie als PDF."},
        {label:"PDF → Bilder",          desc:"Exportiert jede PDF-Seite als PNG-Bild."},
        {label:"PDF organisieren",      desc:"Seiten per Drag-and-Drop neu anordnen oder löschen."},
        {label:"Seiten löschen",        desc:"Bestimmte Seiten aus einem PDF entfernen."},
        {label:"PDF reparieren",        desc:"Re-serialisiert das PDF, um Strukturfehler zu beheben."},
        {label:"HTML → PDF",            desc:"Öffnet die HTML-Datei im Browser und konvertiert sie zu PDF."},
        {label:"PDF abflachen",         desc:"Wandelt ausfüllbare Formularfelder in statischen Text um."},
        {label:"PDF annotieren",        desc:"Fügt Text auf jeder Seite eines PDFs ein."},
        {label:"PDF schwärzen",         desc:"Deckt sensible Bereiche mit schwarzen Rechtecken ab."},
        {label:"OCR durchsuchbar",      desc:"Erstellt ein PDF mit unsichtbarer Textebene für die Ctrl+F-Suche."},
        {label:"Chat mit PDF",          desc:"Chatten Sie mit Ihrem PDF-Inhalt mithilfe künstlicher Intelligenz."},
        {label:"Visueller Editor",      desc:"PDF visuell bearbeiten: Text hinzufügen und Bereiche mit einem Klick schwärzen."},
        {label:"PDF zu Markdown",       desc:"Konvertiert PDF-Text in das Markdown-Format zur direkten Verwendung."},
        {label:"KI-Zusammenfassung",    desc:"Erstellt eine strukturierte Zusammenfassung des PDFs mit künstlicher Intelligenz."},
        {label:"PDFs vergleichen",      desc:"Vergleicht zwei PDFs und hebt Unterschiede Wort für Wort hervor."} ],
    reconvert:"Erneut konvertieren",
    annot_add:"Textannotation hinzufügen",
    annot_text:"Annotationstext…",
    annot_page:"Seite",
    annot_size:"Größe",
    annot_add_btn:"+ Hinzufügen",
    redact_add:"Schwärzungsbereich hinzufügen (in % der Seitengröße)",
    redact_add_btn:"+ Bereich hinzufügen",
    ocr_lang_label:"Dokumentsprache",
    ocr_hint:"OCR lädt Sprachdaten (~4 MB) bei der ersten Nutzung herunter.",
    organize_hint:"Ziehen zum Neuanordnen · Klick auf ✕ zum Entfernen",
    organize_empty:"Keine Seiten mehr vorhanden. Laden Sie die Datei erneut hoch.",
    del_pages_label:"Zu löschende Seiten (z.B. 1-3, 5, 7-9)",
    coming_soon_desc:"Wir arbeiten an diesem Tool. Es wird bald verfügbar sein.",
    coming_soon_toast:"Demnächst verfügbar! Wir arbeiten an diesem Tool.",
    upgrade_pro_reason:"Dieses Tool ist exklusiv für den Pro-Plan.",
    share_hint:"Hat es geholfen? Tool teilen",
    share_native:"Teilen",
    privacy_note:"Deine Datei verlässt nie deinen Browser",
    con_intro:"Fragen oder Probleme? Schreib uns und wir antworten innerhalb von 48 Stunden.",
    con_name:"Name", con_email:"E-Mail", con_subject:"Betreff", con_msg:"Nachricht",
    con_name_ph:"Dein Name", con_email_ph:"du@email.com", con_msg_ph:"Beschreibe es im Detail...",
    con_subjects:[["general","Allgemeine Anfrage"],["bug","Fehler melden"],["feature","Verbesserungsvorschlag"],["api","API-Zugang"],["legal","Rechtliche Frage"]],
    con_send:"Nachricht senden", con_sending:"Senden…", con_cancel:"Abbrechen",
    con_done_title:"Nachricht erhalten",
    con_done_sub:"Wir antworten innerhalb von 48 Werktagen.",
    con_close:"Schließen", con_required:"Bitte alle Felder ausfüllen",
    con_sent:"Nachricht gesendet",
    con_resp_t:"Antwortzeit", con_resp_v:"< 48 Werktage",
    priv_chips:["Kein Tracking","Lokale Verarbeitung","Keine Speicherung"],
    api_beta:"API in privater Beta. Zugang über das Kontaktformular anfordern.",
    api_copy:"Kopieren", api_copied:"✓ Kopiert",
    api_plans:[{t:"Free",r:"50 Req/Monat",s:"10 MB",p:"Kostenlos"},{t:"Pro",r:"5.000 Req/Monat",s:"100 MB",p:"€19/Monat"},{t:"Business",r:"Unbegrenzt",s:"500 MB",p:"€99/Monat"}],
  },
  pt: {
    code:"pt", flag:"🇵🇹", name:"Português",
    tagline:"Sem registo · Sem marcas de água · 100% privado",
    hero_h1a:"A forma mais rápida de", hero_h1b:"converter os teus ficheiros.",
    hero_sub:"PDF, Word, Excel, imagens. Grátis para ficheiros até 10 MB. Os ficheiros ficam sempre no teu browser.",
    hero_cta:"Começar grátis",
    hero_drop:"Arrasta qualquer ficheiro para aqui",
    hero_drop_sub:"Deteção automática da ferramenta",
    tools_title:"Ferramentas", tools_count:"disponíveis",
    detected:"Detetado",
    unknown_fmt:"Formato não reconhecido",
    incompat:"Formato incompatível",
    drag_single:"Arrasta o teu ficheiro para aqui",
    drag_multi:"Arrasta os teus ficheiros para aqui",
    click_hint:"ou clica para selecionar",
    processing:"A processar…",
    convert:"Converter", cancel:"Cancelar",
    download:"Descarregar", other:"Outro ficheiro",
    done_title:"Pronto para descarregar",
    done_sub_s:"ficheiro processado", done_sub_p:"ficheiros processados",
    conv_done:"Conversão concluída",
    dl_started:"Download iniciado",
    pages_label:"Intervalo de páginas (ex: 1-3, 5, 7-9)",
    pages_ph:"Vazio = todas as páginas",
    compress_level:"Nível de compressão",
    q_low:"Leve", q_med:"Média", q_high:"Máxima",
    feat:[ ["Processamento local","Os teus ficheiros não saem do browser."],
           ["Formato preservado","Fontes, margens e tabelas intactas."],
           ["Download imediato","Resultado pronto em segundos."],
           ["Sem publicidade","Plano gratuito sem anúncios."] ],
    free_limit:"O ficheiro excede o limite de 10 MB do plano gratuito.",
    free_batch:"O plano gratuito permite unir até 2 ficheiros. Atualiza para Pro para unir ficheiros ilimitados.",
    free_size:"O ficheiro excede o limite de 10 MB do plano gratuito.",
    upgrade_cta:"Ver planos Pro",
    upgrade_sub:"Ilimitado · Ficheiros até 200 MB · Sem anúncios",
    plan_free:"Gratuito", plan_pro:"Pro",
    plan_free_desc:"Para uso ocasional",
    plan_pro_desc:"Para uso profissional",
    plan_monthly:"por mês", plan_yearly:"por ano",
    plan_save:"Poupa 25%",
    plan_cta_free:"Começar grátis",
    plan_cta_pro:"Começar com Pro",
    plan_current:"Plano atual",
    feat_batch:"Unir até 2 ficheiros",
    merge_hint:"Plano gratuito: máx. 2 ficheiros. Atualiza para Pro para mais.",
    feat_size_free:"Ficheiros até 10 MB",
    feat_size_pro:"Ficheiros até 200 MB",
    feat_tools:"Todas as ferramentas",
    feat_unlimited:"Unir ficheiros ilimitados",
    feat_noad:"Sem anúncios",
    feat_priority:"Processamento prioritário",
    pricing_title:"Preços simples e transparentes",
    pricing_sub:"Sem contratos. Cancela quando quiseres.",
    how_title:"Como funciona?", how_sub:"Sem instalação, sem registo, os teus ficheiros não saem do dispositivo.",
    how_steps:[["Escolhe a tua ferramenta","Seleciona a conversão que precisas — PDF, Word, imagens, Excel e mais."],["Carrega o teu ficheiro","Arrasta o ficheiro ou clica para selecionar. Até 10 MB no plano gratuito."],["Descarrega o resultado","A conversão acontece no teu browser. Descarrega o ficheiro em segundos."]],
    faq_title:"Perguntas frequentes", faq:[
      ["É completamente gratuito?", "O plano gratuito inclui todas as ferramentas sem registo, para ficheiros até 10 MB e união de até 2 PDFs. O Pro aumenta o limite para 200 MB e permite união ilimitada."],
      ["Os meus ficheiros são enviados para um servidor?", "Não. Tudo acontece no browser via WebAssembly. Os teus ficheiros nunca saem do teu dispositivo."],
      ["Que formatos posso converter?", "PDF, Word (DOCX), Excel (XLSX), PowerPoint (PPTX), imagens (JPG, PNG, WEBP). Une, divide, comprime, roda ou organiza PDFs."],
      ["Existe limite de tamanho?", "No plano gratuito o limite é de 10 MB por ficheiro. Com Pro podes converter ficheiros até 200 MB."],
      ["Funciona no telemóvel?", "Sim, em qualquer dispositivo com um browser moderno: computador, tablet ou telemóvel."],
      ["Posso carregar vários ficheiros de uma vez?", "Para unir PDFs sim. As outras ferramentas processam um ficheiro de cada vez."],
      ["Funciona sem ligação à internet?", "As conversões de PDF, Word e imagens funcionam completamente offline após carregar a página. O OCR e algumas funções externas requerem ligação."],
      ["Que browsers são suportados?", "Chrome, Edge, Firefox e Safari (últimas 2 versões principais). Chrome ou Edge são recomendados para a melhor experiência."],
      ["Posso converter PDFs protegidos com palavra-passe?", "morf pode remover restrições de proprietário (edição/impressão) com a ferramenta 'Desbloquear PDF'. PDFs cifrados com palavra-passe de abertura não podem ser processados."],
      ["O que acontece se a conversão falhar?", "Receberás uma mensagem de erro descritiva. As causas mais comuns são ficheiros corrompidos ou PDFs muito complexos. Se o problema persistir, contacta-nos."]
    ],
    max_size:"máx. 200 MB",
    counter:"ficheiros convertidos",
    step_read:"A ler ficheiro…", step_proc:"A processar…", step_done:"Pronto!",
    hist_title:"Conversões recentes", hist_empty:"Ainda não converteste nenhum ficheiro.", hist_clear:"Limpar histórico",
    nav_privacy:"Privacidade", nav_api:"API", nav_help:"Ajuda",
    footer_copy:"morf · © 2026",
    footer_tools:"Ferramentas populares", footer_company:"Empresa",
    search_ph:"Procurar ferramenta…",
    cat_conv:"Conversão de documentos", cat_img:"Imagens",
    cat_ops:"Operações PDF", cat_edit:"Edição PDF", cat_sec:"Segurança e avançado",
    stat_files:"ficheiros convertidos", stat_speed:"velocidade média", stat_priv:"sempre privado",
    tools_more:"Ver todas as ferramentas", tools_less:"Mostrar menos",
    plan_annual_total:"Faturado 53,88 €/ano · poupa 18 €",
    trust_browser:"100% no browser", trust_noreg:"Sem registo", trust_free:"Sempre grátis",
    next_tool:"Experimenta também",
    home_drop_title:"O que queres fazer?", home_drop_sub:"Escolhe uma ferramenta compatível com o teu ficheiro",
    modal_contact:"Contacto", modal_api:"API morf",
    err_title:"Não foi possível completar a conversão",
    err_retry:"Tentar novamente",
    err_size:"O ficheiro excede o limite de 200 MB. Usa um ficheiro mais pequeno.",
    err_protected:"Este PDF está protegido por palavra-passe. Remove-a antes de converter.",
    err_corrupt:"O ficheiro parece estar corrompido ou não é um formato válido.",
    err_range:"Intervalo de páginas inválido. Usa o formato 1-3, 5, 7-9.",
    err_popup:"O browser bloqueou a janela pop-up. Permite pop-ups e tenta novamente.",
    err_generic:"Ocorreu um erro inesperado. Verifica se o ficheiro não está corrompido.",
    err_suggest:"Continua a falhar? Escreve-nos para hola@morf.app",
    err_odt:"Formato ODT detetado. Abre-o no LibreOffice e guarda como .docx (Ficheiro → Guardar como → Word 2007-365) e tenta novamente.",
    watermark_label:"Texto da marca de água",
    crop_label:"Margens a recortar (mm)",
    crop_top:"Cima", crop_bottom:"Baixo", crop_left:"Esquerda", crop_right:"Direita",
    sign_label:"Desenha a tua assinatura",
    sign_hint:"A assinatura será colocada no canto inferior direito da última página.",
    t:[ {label:"PDF → Word",          desc:"Converte PDF em documento Word editável."},
        {label:"Word → PDF",          desc:"Transforma Word em PDF de alta fidelidade."},
        {label:"Imagem → PDF",        desc:"Agrupa JPG, PNG ou WEBP num único PDF."},
        {label:"Unir PDFs",           desc:"Combina vários PDFs respeitando a ordem."},
        {label:"Dividir PDF",         desc:"Extrai páginas ou intervalos de qualquer PDF."},
        {label:"Comprimir PDF",       desc:"Reduz o tamanho sem perda visível de qualidade."},
        {label:"PNG → JPG",           desc:"Converte imagens PNG para formato JPG."},
        {label:"JPG → PNG",           desc:"Converte imagens JPG para formato PNG."},
        {label:"Rodar PDF",           desc:"Roda páginas do PDF 90°, 180° ou 270°."},
        {label:"Excel → PDF",         desc:"Converte folhas de cálculo Excel em PDF."},
        {label:"PDF → PowerPoint",    desc:"Converte cada página do PDF numa diapositiva PPTX.", popular:true},
        {label:"PDF → Excel",         desc:"Extrai o texto do PDF para uma folha Excel.", popular:true},
        {label:"Marca de água PDF",   desc:"Adiciona texto diagonal de marca de água em todas as páginas."},
        {label:"Numerar páginas",     desc:"Insere o número de página no rodapé de cada folha."},
        {label:"Recortar PDF",        desc:"Recorta as margens de todas as páginas do PDF."},
        {label:"PDF em tons de cinza",desc:"Converte o PDF para tons de cinza."},
        {label:"Desbloquear PDF",     desc:"Remove as restrições de um PDF protegido."},
        {label:"Assinar PDF",         desc:"Desenha a tua assinatura e adiciona-a à última página."},
        {label:"OCR PDF",             desc:"Extrai texto de PDFs digitalizados com reconhecimento ótico.", pro:true},
        {label:"Proteger PDF",        desc:"Adiciona palavra-passe a um PDF para restringir o acesso.", comingSoon:true},
        {label:"PPTX → PDF",          desc:"Extrai o conteúdo de cada diapositivo PowerPoint para PDF."},
        {label:"PDF → Imagens",       desc:"Exporta cada página do PDF como imagem PNG."},
        {label:"Organizar PDF",       desc:"Reorganize ou remova páginas por arrastar e soltar."},
        {label:"Excluir páginas",     desc:"Remova páginas específicas de um PDF."},
        {label:"Reparar PDF",         desc:"Re-serializa o PDF para corrigir erros de estrutura."},
        {label:"HTML → PDF",          desc:"Abre o ficheiro HTML no browser e converte-o para PDF."},
        {label:"Aplanar PDF",         desc:"Converte campos de formulário preenchíveis em texto estático."},
        {label:"Anotar PDF",          desc:"Adiciona texto em qualquer página de um PDF."},
        {label:"Redigir PDF",         desc:"Cobre áreas sensíveis com rectângulos pretos."},
        {label:"OCR Pesquisável",     desc:"Cria um PDF com camada de texto invisível para pesquisa com Ctrl+F."},
        {label:"Chat com PDF",        desc:"Converse com o conteúdo do PDF usando inteligência artificial."},
        {label:"Editor Visual",       desc:"Edite o PDF visualmente: adicione texto e redija zonas com um clique."},
        {label:"PDF para Markdown",   desc:"Converte o texto do PDF para formato Markdown pronto a usar."},
        {label:"Resumir com IA",      desc:"Gera um resumo estruturado do PDF usando inteligência artificial."},
        {label:"Comparar PDFs",       desc:"Compara dois PDFs e destaca as diferenças palavra a palavra."} ],
    reconvert:"Converter de novo",
    annot_add:"Adicionar anotação de texto",
    annot_text:"Texto da anotação…",
    annot_page:"Página",
    annot_size:"Tamanho",
    annot_add_btn:"+ Adicionar",
    redact_add:"Adicionar zona de redacção (em % do tamanho da página)",
    redact_add_btn:"+ Adicionar zona",
    ocr_lang_label:"Idioma do documento",
    ocr_hint:"O OCR irá descarregar os dados do idioma (~4 MB) na primeira utilização.",
    organize_hint:"Arrastar para reordenar · Clic ✕ para remover",
    organize_empty:"Sem páginas restantes. Volte a carregar o ficheiro.",
    del_pages_label:"Páginas a excluir (ex. 1-3, 5, 7-9)",
    coming_soon_desc:"Estamos a trabalhar nesta ferramenta. Estará disponível em breve.",
    coming_soon_toast:"Em breve! Estamos a trabalhar nesta ferramenta.",
    upgrade_pro_reason:"Esta ferramenta é exclusiva do plano Pro.",
    share_hint:"Foi útil? Partilha esta ferramenta",
    share_native:"Partilhar",
    privacy_note:"O teu ficheiro nunca sai do teu browser",
    con_intro:"Tens alguma dúvida? Escreve-nos e respondemos em menos de 48h úteis.",
    con_name:"Nome", con_email:"E-mail", con_subject:"Assunto", con_msg:"Mensagem",
    con_name_ph:"O teu nome", con_email_ph:"tu@email.com", con_msg_ph:"Descreve em detalhe...",
    con_subjects:[["general","Consulta geral"],["bug","Reportar erro"],["feature","Sugestão"],["api","Acesso à API"],["legal","Assunto legal"]],
    con_send:"Enviar mensagem", con_sending:"A enviar…", con_cancel:"Cancelar",
    con_done_title:"Mensagem recebida",
    con_done_sub:"Respondemos em menos de 48 horas úteis.",
    con_close:"Fechar", con_required:"Preenche todos os campos",
    con_sent:"Mensagem enviada",
    con_resp_t:"Resposta", con_resp_v:"< 48h úteis",
    priv_chips:["Sem rastreio","Processamento local","Sem armazenamento"],
    api_beta:"API em beta privada. Solicita acesso no formulário de contacto.",
    api_copy:"Copiar", api_copied:"✓ Copiado",
    api_plans:[{t:"Free",r:"50 req/mês",s:"10 MB",p:"Grátis"},{t:"Pro",r:"5.000 req/mês",s:"100 MB",p:"€19/mês"},{t:"Business",r:"Ilimitado",s:"500 MB",p:"€99/mês"}],
  },
};

// eslint-disable-next-line react-refresh/only-export-components
export function detectLang() {
  const nav = (navigator.language || navigator.userLanguage || "en").toLowerCase().slice(0,2);
  return LANGS[nav] ? nav : "en";
}

// eslint-disable-next-line react-refresh/only-export-components
export const LangCtx = createContext(null);
// eslint-disable-next-line react-refresh/only-export-components
export const useLang = () => useContext(LangCtx);

export { LANGS };
